{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2022-40811",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "NVD-CWE-Other"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://pypi.org/project/democritus-file-system/",
        "name": "https://pypi.org/project/democritus-file-system/",
        "refsource": "MISC",
        "tags": [
          "Not Applicable"
        ]
      },
      {
        "url": "https://github.com/democritus-project/d8s-urls/issues/11",
        "name": "https://github.com/democritus-project/d8s-urls/issues/11",
        "refsource": "MISC",
        "tags": [
          "Exploit",
          "Issue Tracking",
          "Third Party Advisory"
        ]
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "The d8s-urls for python, as distributed on PyPI, included a potential code-execution backdoor inserted by a third party. The backdoor is the democritus-file-system package. The affected version is 0.1.0."
      }
    ]
  }
}