{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2017-1000433",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-287"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://github.com/rohe/pysaml2/issues/451",
        "name": "https://github.com/rohe/pysaml2/issues/451",
        "refsource": "CONFIRM",
        "tags": [
          "Patch",
          "Third Party Advisory",
          "VDB Entry"
        ]
      },
      {
        "url": "https://security.gentoo.org/glsa/201801-11",
        "name": "GLSA-201801-11",
        "refsource": "GENTOO",
        "tags": [
          "Issue Tracking",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.debian.org/debian-lts-announce/2018/07/msg00000.html",
        "name": "[debian-lts-announce] 20180701 [SECURITY] [DLA 1410-1] python-pysaml2 security update",
        "refsource": "MLIST",
        "tags": [
          "Mailing List",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.debian.org/debian-lts-announce/2021/02/msg00038.html",
        "name": "[debian-lts-announce] 20210226 [SECURITY] [DLA 2577-1] python-pysaml2 security update",
        "refsource": "MLIST",
        "tags": [
          "Mailing List",
          "Third Party Advisory"
        ]
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "pysaml2 version 4.4.0 and older accept any password when run with python optimizations enabled. This allows attackers to log in as any user without knowing their password."
      }
    ]
  }
}