{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2018-6611",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-125"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://lib.openmpt.org/libopenmpt/2018/02/03/security-update-0.3.6/",
        "name": "https://lib.openmpt.org/libopenmpt/2018/02/03/security-update-0.3.6/",
        "refsource": "CONFIRM",
        "tags": [
          "Patch",
          "Release Notes",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://github.com/OpenMPT/openmpt/commit/b60b322cf9f0ffa624018f1bb9783edf0dc908c3",
        "name": "https://github.com/OpenMPT/openmpt/commit/b60b322cf9f0ffa624018f1bb9783edf0dc908c3",
        "refsource": "CONFIRM",
        "tags": [
          "Patch",
          "Vendor Advisory"
        ]
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "soundlib/Load_stp.cpp in OpenMPT through 1.27.04.00, and libopenmpt before 0.3.6, has an out-of-bounds read via a malformed STP file."
      }
    ]
  }
}