{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2016-2964",
    "ASSIGNER": "psirt@us.ibm.com"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-200"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/113813",
        "name": "https://exchange.xforce.ibmcloud.com/vulnerabilities/113813",
        "refsource": "MISC",
        "tags": [
          "VDB Entry",
          "Vendor Advisory"
        ]
      },
      {
        "url": "http://www.ibm.com/support/docview.wss?uid=swg22006441",
        "name": "http://www.ibm.com/support/docview.wss?uid=swg22006441",
        "refsource": "CONFIRM",
        "tags": [
          "Patch",
          "Vendor Advisory"
        ]
      },
      {
        "url": "http://www.securityfocus.com/bid/100572",
        "name": "100572",
        "refsource": "BID",
        "tags": []
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "IBM Sametime 8.5.2 and 9.0 under certain conditions provides an error message to a user that is too detailed and may reveal details about the application. IBM X-Force ID: 113813."
      }
    ]
  }
}