{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2013-2027",
    "ASSIGNER": "secalert@redhat.com"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-264"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=947949",
        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=947949",
        "refsource": "MISC",
        "tags": [
          "Issue Tracking"
        ]
      },
      {
        "url": "http://lists.opensuse.org/opensuse-updates/2015-02/msg00055.html",
        "name": "openSUSE-SU-2015:0269",
        "refsource": "SUSE",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2015:158",
        "name": "MDVSA-2015:158",
        "refsource": "MANDRIVA",
        "tags": [
          "Broken Link"
        ]
      },
      {
        "url": "http://advisories.mageia.org/MGASA-2015-0096.html",
        "name": "http://advisories.mageia.org/MGASA-2015-0096.html",
        "refsource": "CONFIRM",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://www.oracle.com/technetwork/security-advisory/cpujul2017-3236622.html",
        "name": "http://www.oracle.com/technetwork/security-advisory/cpujul2017-3236622.html",
        "refsource": "CONFIRM",
        "tags": []
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "Jython 2.2.1 uses the current umask to set the privileges of the class cache files, which allows local users to bypass intended access restrictions via unspecified vectors."
      }
    ]
  }
}