{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2022-33002",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "NVD-CWE-noinfo"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://pypi.org/project/kgexplore/",
        "name": "https://pypi.org/project/kgexplore/",
        "refsource": "MISC",
        "tags": [
          "Product"
        ]
      },
      {
        "url": "http://pypi.doubanio.com/simple/request",
        "name": "http://pypi.doubanio.com/simple/request",
        "refsource": "MISC",
        "tags": [
          "Product"
        ]
      },
      {
        "url": "https://github.com/smoothnlp/KGExplore/issues/13",
        "name": "https://github.com/smoothnlp/KGExplore/issues/13",
        "refsource": "MISC",
        "tags": [
          "Exploit",
          "Issue Tracking",
          "Third Party Advisory"
        ]
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "The KGExplore package in PyPI v0.1.1 to v0.1.2 was discovered to contain a code execution backdoor via the request package. This vulnerability allows attackers to access sensitive user information and digital currency keys, as well as escalate privileges."
      }
    ]
  }
}