{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2018-9144",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-125"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://github.com/xiaoqx/pocs/tree/master/exiv2",
        "name": "https://github.com/xiaoqx/pocs/tree/master/exiv2",
        "refsource": "MISC",
        "tags": [
          "Exploit",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/Exiv2/exiv2/issues/254",
        "name": "https://github.com/Exiv2/exiv2/issues/254",
        "refsource": "MISC",
        "tags": [
          "Exploit",
          "Issue Tracking",
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://security.gentoo.org/glsa/201811-14",
        "name": "GLSA-201811-14",
        "refsource": "GENTOO",
        "tags": [
          "Third Party Advisory"
        ]
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "In Exiv2 0.26, there is an out-of-bounds read in Exiv2::Internal::binaryToString in image.cpp. It could result in denial of service or information disclosure."
      }
    ]
  }
}