{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2011-4211",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-264"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "http://blog.watchfire.com/files/googleappenginesdk.pdf",
        "name": "http://blog.watchfire.com/files/googleappenginesdk.pdf",
        "refsource": "MISC",
        "tags": [
          "Exploit"
        ]
      },
      {
        "url": "http://code.google.com/p/googleappengine/wiki/SdkReleaseNotes",
        "name": "http://code.google.com/p/googleappengine/wiki/SdkReleaseNotes",
        "refsource": "MISC",
        "tags": [
          "Patch"
        ]
      },
      {
        "url": "http://www.securityfocus.com/bid/50464",
        "name": "50464",
        "refsource": "BID",
        "tags": []
      },
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/71064",
        "name": "google-app-fakefile-priv-esc(71064)",
        "refsource": "XF",
        "tags": []
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "The FakeFile implementation in the sandbox environment in the Google App Engine Python SDK before 1.5.4 does not properly control the opening of files, which allows local users to bypass intended access restrictions and create arbitrary files via ALLOWED_MODES and ALLOWED_DIRS changes within the code parameter to _ah/admin/interactive/execute, a different vulnerability than CVE-2011-1364."
      }
    ]
  }
}