{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2024-0193",
    "ASSIGNER": "secalert@redhat.com"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-416"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://access.redhat.com/security/cve/CVE-2024-0193",
        "name": "https://access.redhat.com/security/cve/CVE-2024-0193",
        "refsource": "",
        "tags": [
          "Mitigation",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2255653",
        "name": "RHBZ#2255653",
        "refsource": "",
        "tags": [
          "Issue Tracking",
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://access.redhat.com/errata/RHSA-2024:1018",
        "name": "RHSA-2024:1018",
        "refsource": "",
        "tags": []
      },
      {
        "url": "https://access.redhat.com/errata/RHSA-2024:1019",
        "name": "RHSA-2024:1019",
        "refsource": "",
        "tags": []
      },
      {
        "url": "https://access.redhat.com/errata/RHSA-2024:1248",
        "name": "RHSA-2024:1248",
        "refsource": "",
        "tags": []
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "A use-after-free flaw was found in the netfilter subsystem of the Linux kernel. If the catchall element is garbage-collected when the pipapo set is removed, the element can be deactivated twice. This can cause a use-after-free issue on an NFT_CHAIN object or NFT_OBJECT object, allowing a local unprivileged user with CAP_NET_ADMIN capability to escalate their privileges on the system."
      }
    ]
  }
}