{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2015-8549",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-611"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "http://www.securityfocus.com/archive/1/archive/1/537151/100/0/threaded",
        "name": "http://www.securityfocus.com/archive/1/archive/1/537151/100/0/threaded",
        "refsource": "MISC",
        "tags": [
          "Broken Link"
        ]
      },
      {
        "url": "https://github.com/hydralabs/pyamf/releases/tag/v0.8.0",
        "name": "https://github.com/hydralabs/pyamf/releases/tag/v0.8.0",
        "refsource": "MISC",
        "tags": [
          "Release Notes"
        ]
      },
      {
        "url": "https://github.com/hydralabs/pyamf/pull/58",
        "name": "https://github.com/hydralabs/pyamf/pull/58",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://www.ocert.org/advisories/ocert-2015-011.html",
        "name": "http://www.ocert.org/advisories/ocert-2015-011.html",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "XML external entity (XXE) vulnerability in PyAMF before 0.8.0 allows remote attackers to cause a denial of service or read arbitrary files via a crafted Action Message Format (AMF) payload."
      }
    ]
  }
}