{
  "data_type": "CVE",
  "data_format": "MITRE",
  "data_version": "4.0",
  "CVE_data_meta": {
    "ID": "CVE-2015-8538",
    "ASSIGNER": "cve@mitre.org"
  },
  "problemtype": {
    "problemtype_data": [
      {
        "description": [
          {
            "lang": "en",
            "value": "CWE-20"
          }
        ]
      }
    ]
  },
  "references": {
    "reference_data": [
      {
        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1291299",
        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1291299",
        "refsource": "CONFIRM",
        "tags": [
          "Issue Tracking"
        ]
      },
      {
        "url": "http://www.openwall.com/lists/oss-security/2015/12/10/3",
        "name": "[oss-security] 20151210 Re: CVE request - a out of bound read bug is found in libdwarf",
        "refsource": "MLIST",
        "tags": [
          "Mailing List",
          "Third Party Advisory"
        ]
      }
    ]
  },
  "description": {
    "description_data": [
      {
        "lang": "en",
        "value": "dwarf_leb.c in libdwarf allows attackers to cause a denial of service (SIGSEGV)."
      }
    ]
  }
}